services:
    vscode-server:
        container_name: vscode-server
        hostname: vscode
        ports:
            - '8000:8000'
        environment:
            - VSCODE_KEYRING_PASS=mysecretpassword
            - VSCODE_SERVE_MODE=serve-local
        volumes:
            - './data:/root/.vscode-server'
        build: .
        
